### ISSUE TITLE
Figure out how to mount ssh files into remote build container

### ISSUE THREAD

**Issue by JayNewstrom** [JayNewstrom/DockerGradleAndroid#4]
`~/.ssh/authorized_keys`
`/etc/ssh/ssh_host_rsa_key`
`/etc/ssh/ssh_host_rsa_key.pub`

These files should be persisted on the host, and mounted into the container.

`docker-compose.yml` might look something like this:
```
version: '3.4'

services:
  remote-build:
    image: jaynewstrom/alpine-gradle-android-remote-build:gradle-6.2.2_agp-3.6.1
    restart: always
    volumes:
      - ./remoteBuild/gradle.properties:/root/.gradle/gradle.properties:ro
      - ./remoteBuild/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./remoteBuild/ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      - ./.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    ports:
      - '2222:22'
```

There is a problem (I think related to permissions/file ownership), that prevents this from working.
